# Generated by Django 6.0.2 on 2026-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='menu_items/'),
        ),
    ]
